version: "3"

volumes:
    prometheus_data: {}
    grafana_data: {}

services:
    prometheus:
      image: prom/prometheus:v2.1.0
      volumes:
        - ./prometheus.yaml:/etc/prometheus/prometheus.yaml
      command:
        - '--config.file=/etc/prometheus/prometheus.yaml'
      ports:
        - '9090:9090'

    grafana:
      image: grafana/grafana
      volumes:
        - grafana_data:/var/lib/grafana
      environment:
        - GF_SECURITY_ADMIN_PASSWORD=pass
      depends_on:
        - prometheus
      ports:
        - '3000:3000'

    redis:
        hostname: redis
        image: redis
        ports:
            - "6379:6379" 
        restart: always
    
    mongodb:
        hostname: mongodb
        image: mongo:4.0.8
        ports:
          - "27017:27017"

    flask:
        container_name: flask
        build: 
          context: ../
          dockerfile: Dockerfile
        depends_on:
          - redis
        command: supervisord -n
        env_file: hotel.env
        expose:
            - "8700"
        sysctls:
            - net.core.somaxconn=4096
        ports:
            - "8700:8700"
            # celery-flower
            - "5001:5001"
            # uwsgitop
            - "5002:5002"
            # supervisor
            - "9002:9002"
            - "9200:9200"
    nginx:
      container_name: nginx
      build:
        context: ../
        dockerfile: docker_nginx
      command: 
          nginx -g 'daemon off;' 
      depends_on:
        - flask
      ports:
        - "80:80" 
      volumes:
        - ./nginx/nginx.conf:/etc/nginx/sites-enabled/nginx.conf
        - ./nginx/site_enabled/default.conf:/etc/nginx/conf.d/default.conf
      logging:
          driver: syslog
          options:
            tag: nginx
            syslog-address: "tcp://logstash:5000"
      restart: always
