version: "2"
services:
    redis:
        hostname: redis
        image: redis
        ports:
            - "6379:6379" 
        restart: always
    
    mongodb:
        hostname: mongodb
        image: mongo:4.0.8
        ports:
          - "27017:27017"

    flask:
        container_name: flask
        build: 
          context: ../
          dockerfile: Dockerfile
        depends_on:
          - redis
        command: supervisord -n
        env_file: hotel.env
        expose:
            - "8700"
        ports:
            - "8700:8700"
            # celery-flower
            - "5001:5001"
            # uwsgitop
            - "5002:5002"
        logging:
            driver: "json-file"
            options:
                max-size: "50m"
        restart: always

    nginx:
      container_name: nginx
      build:
        context: ../
        dockerfile: docker_nginx
      command: 
          nginx -g 'daemon off;' 
      depends_on:
        - flask
      ports:
        - "80:80" 
      volumes:
        - ./nginx/nginx.conf:/etc/nginx/sites-enabled/nginx.conf
        - ./nginx/site_enabled/default.conf:/etc/nginx/conf.d/default.conf
      restart: always